using System.Data;
using System.Data.Common;
using System.Data.SQLite;
using DotEnv.SourceGenerator;
using Npgsql;

namespace VolleyList.Database;

public interface IDbConnectionProvider
{
    public DbConnection GetDbConnection();
}

[DotEnvAutoGenerated]
public static partial class SupabaseVariables
{
    public static partial string SupabaseHost { get; }
    public static partial int SupabasePort { get; }
    public static partial string SupabaseUser { get; }
    public static partial string SupabasePassword { get; }
    public static partial string SupabaseDatabase { get; }
}

[DotEnvAutoGenerated]
public static partial class SqliteVariables
{
    public static partial string SqlitePath { get; }
}

public class SupabaseConnectionProvider : IDbConnectionProvider
{
    private readonly NpgsqlConnectionStringBuilder _builder = new()
    {
        Host = SupabaseVariables.SupabaseHost,
        Port = SupabaseVariables.SupabasePort,
        Username = SupabaseVariables.SupabaseUser,
        Password = SupabaseVariables.SupabasePassword,
        Database = SupabaseVariables.SupabaseDatabase,
    };

    public DbConnection GetDbConnection()
    {
        return new NpgsqlConnection(_builder.ConnectionString);
    }
}

public class SqliteConnectionProvider : IDbConnectionProvider
{
    public DbConnection GetDbConnection()
    {
        return new SQLiteConnection($"Data Source={SqliteVariables.SqlitePath}");
    }
}

public class DatabaseContext(IDbConnectionProvider dbConnectionProvider)
{
    public async Task<T> WithConnectionAsync<T>(Func<IDbConnection, Task<T>> callback,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(callback);

        await using var conn = dbConnectionProvider.GetDbConnection();

        return await callback(conn);
    }

    public async Task<T> WithTransactionAsync<T>(Func<IDbConnection, IDbTransaction, Task<T>> callback,
        IsolationLevel isolationLevel = IsolationLevel.Unspecified,
        CancellationToken cancellationToken = default)
    {
        await using var conn = dbConnectionProvider.GetDbConnection();
        await conn.OpenAsync(cancellationToken);
        await using var transaction = await conn.BeginTransactionAsync(isolationLevel, cancellationToken);

        var result = await callback(conn, transaction);

        await transaction.CommitAsync(cancellationToken);

        return result;
    }
}